### ISSUE TITLE
Testing in packages

### ISSUE THREAD

**Issue by andrewmclagan** [janhenkgerritsen/codeception-laravel5-sample#1]
Is there documentation on how to use this module to test packages during development. E.g. running packages migrations etc...

**Comment by janhenkgerritsen** [comment]
This is the repository of the sample app, you can find the repository for the actual module here:

https://github.com/janhenkgerritsen/codeception-laravel5

This module is an adaptation of the current [Laravel4](http://codeception.com/docs/modules/Laravel4) module for Codeception and usage is similar.

Currently documentation is only available in the [Laravel5 module](https://github.com/janhenkgerritsen/codeception-laravel5/blob/master/src/Codeception/Module/Laravel5.php) file. However, when this module is incorporated into Codeception this documenation will also be available through the Codeception website.
